pipelines:
  - name: affinity_pipeline
    setup:
      runtime: onHost
    steps:
      - name: step1
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker_kirti
        execution:
          onExecute:
            - echo "executing...it"
      - name: step2
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker_kirti
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step1
      - name: step3
        type: bash
        configuration:
          affinityGroup: group2
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker_kirti
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step2
      - name: step4
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker_kirti
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step1
      - name: step5
        type: bash
        configuration:
          affinityGroup: group2
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 1
            custom:
              name: test
              tag:  test
              options: test
        requires:
          integrations:
            - docker_kirti
        execution:
          onExecute:
            - echo "executing..."
        triggeredBy:
          steps:
            - step2
